# Generated by Django 5.1.3 on 2025-03-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_fooddatabase_remove_food_calories_remove_food_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddatabase',
            name='measurement',
            field=models.CharField(choices=[('Per gram', 'Per gram'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('Extra Large', 'Extra Large'), ('Jumbo', 'Jumbo')], max_length=50),
        ),
    ]
