# Generated by Django 5.1.3 on 2025-03-16 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_foodintake_delete_food'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionalTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calorie_target', models.FloatField(default=0.0)),
                ('protein_target', models.FloatField(default=0.0)),
                ('carbs_target', models.FloatField(default=0.0)),
                ('fats_target', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CalorieBudget',
        ),
    ]
