# Generated by Django 5.1.3 on 2025-03-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_nutritionaltarget_delete_caloriebudget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddatabase',
            name='calcium',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='fooddatabase',
            name='cholesterol',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='fooddatabase',
            name='dietary_fiber',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='fooddatabase',
            name='iron',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='fooddatabase',
            name='monounsaturated_fat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='fooddatabase',
            name='net_carbs',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='fooddatabase',
            name='polyunsaturated_fat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='fooddatabase',
            name='potassium',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='fooddatabase',
            name='sodium',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='fooddatabase',
            name='total_sugars',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='fooddatabase',
            name='trans_fat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='fooddatabase',
            name='vitamin_a',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='fooddatabase',
            name='vitamin_c',
            field=models.FloatField(default=0.0),
        ),
    ]
