# Generated by Django 5.1.3 on 2025-03-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_fooddatabase_calcium_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddatabase',
            name='measurement',
            field=models.CharField(choices=[('Per gram', 'Per gram'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('Extra Large', 'Extra Large'), ('Jumbo', 'Jumbo'), ('Per serving (150 g)', 'Per serving (150 g)'), ('Per serving (300 g)', 'Per serving (300 g)'), ('Per slice (100 g)', 'Per slice (100 g)'), ('Per slice (98.0 g)', 'Per slice (98.0 g)'), ('Per serving (82.3 g)', 'Per serving (82.3 g)'), ('Per slice (83.1 g)', 'Per slice (83.1 g)'), ('Per slice (76.8 g)', 'Per slice (76.8 g)'), ('Per slice (102 g)', 'Per slice (102 g)'), ('Per serving (135 g)', 'Per serving (135 g)'), ('Per piece (20 g)', 'Per piece (20 g)')], max_length=50),
        ),
    ]
