# Generated by Django 5.1.3 on 2025-03-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_runningactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionaltarget',
            name='calories_burned_goal',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='nutritionaltarget',
            name='steps_goal',
            field=models.IntegerField(default=0),
        ),
    ]
