# Generated by Django 5.1.3 on 2025-03-30 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_nutritionaltarget_calories_burned_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodintake',
            name='manual_calories',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodintake',
            name='manual_carbs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodintake',
            name='manual_fats',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodintake',
            name='manual_protein',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodintake',
            name='food_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.fooddatabase'),
        ),
        migrations.AlterField(
            model_name='foodintake',
            name='meal_type',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack')], default='Lunch', max_length=20),
        ),
        migrations.AlterField(
            model_name='foodintake',
            name='serving_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
