# Generated by Django 5.1.3 on 2025-04-05 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_foodintake_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CyclingActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('duration', models.DurationField()),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=5)),
                ('avg_speed_kmh', models.DecimalField(decimal_places=1, max_digits=4)),
                ('max_speed_kmh', models.DecimalField(decimal_places=1, max_digits=4)),
                ('elevation_gain_m', models.PositiveIntegerField(default=0)),
                ('calories_burned', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
