# Generated by Django 5.1.3 on 2025-04-10 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_reminder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooddatabase',
            name='measurement',
        ),
        migrations.CreateModel(
            name='FoodMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('gram_equivalent', models.FloatField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='api.fooddatabase')),
            ],
        ),
    ]
