# Generated by Django 5.1.3 on 2025-04-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_fooddatabase_calcium_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysteps',
            name='steps',
            field=models.IntegerField(default=0),
        ),
    ]
