# Generated by Django 5.1.3 on 2025-04-10 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_dailysteps_steps'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailySteps',
        ),
    ]
