# Generated by Django 5.1.3 on 2025-04-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_walkingactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodintake',
            name='name',
            field=models.CharField(blank=True, default='Custom Meal', max_length=100, null=True),
        ),
    ]
