# Generated by Django 5.1.3 on 2025-04-23 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_foodintake_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='runningactivity',
            name='route_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
