# Generated by Django 5.1.3 on 2025-04-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_walkingactivity_route_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyclingactivity',
            name='route_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
