# Generated by Django 5.1.3 on 2025-03-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activity_level',
            field=models.CharField(choices=[('Sedentary', 'Sedentary'), ('Low Active', 'Low Active'), ('Active', 'Active'), ('Very Active', 'Very Active')], default='Sedentary', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='goal',
            field=models.CharField(choices=[('Weight Gain', 'Weight Gain'), ('Maintain Weight', 'Maintain Weight'), ('Weight Loss', 'Weight Loss')], default='Maintain Weight', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='target_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='timeline',
            field=models.CharField(blank=True, choices=[('Weeks', 'Weeks'), ('Months', 'Months')], max_length=20, null=True),
        ),
    ]
